# permissions for end users to view configzones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configzone-viewer-role
rules:
- apiGroups:
  - hepa.erda.cloud
  resources:
  - configzones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hepa.erda.cloud
  resources:
  - configzones/status
  verbs:
  - get
