# permissions for end users to edit configzones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configzone-editor-role
rules:
- apiGroups:
  - hepa.erda.cloud
  resources:
  - configzones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hepa.erda.cloud
  resources:
  - configzones/status
  verbs:
  - get
