# permissions for end users to view hapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hapi-viewer-role
rules:
- apiGroups:
  - hepa.erda.cloud
  resources:
  - hapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hepa.erda.cloud
  resources:
  - hapis/status
  verbs:
  - get
