# permissions for end users to edit kongresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kongress-editor-role
rules:
- apiGroups:
  - hepa.erda.cloud
  resources:
  - kongresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hepa.erda.cloud
  resources:
  - kongresses/status
  verbs:
  - get
