# kubectl -n hapi-operator-sample get czr,hapi,ing,svc,deploy,pod

apiVersion: v1
kind: Namespace
metadata:
  name: hapi-operator-sample
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-httpbin
  namespace: hapi-operator-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-httpbin
  template:
    metadata:
      labels:
        app: go-httpbin
        version: v1
    spec:
      containers:
        - image: registry.cn-hangzhou.aliyuncs.com/dspo/go-httpbin:20220927-114741-7a8cd39
          env:
            - name: EXPOSE_PORT
              value: "8090"
          imagePullPolicy: Always
          name: go-httpbin
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: go-httpbin
  namespace: hapi-operator-sample
spec:
  ports:
    - port: 80
      targetPort: 8090
      protocol: TCP
  selector:
    app: go-httpbin

---
apiVersion: hepa.erda.cloud/v1
kind: ConfigZone
metadata:
  name: hapi-operator-sample
  namespace: hapi-operator-sample
spec:
  policy:
    auth:
      authType: hmac-auth
      switch: true
    safetyIP:
      blackListSourceRange: ""
      domainBlackListSourceRange: ""
      domainWhiteListSourceRange: ""
      ipType: x-peer-ip
      keyRateLimitingValue: 10 query_per_second
      switch: true
      whiteListSourceRange: 123.45.67.1/16,10.10.10.10

---
apiVersion: hepa.erda.cloud/v1
kind: Hapi
metadata:
  name: hapi-sample
  namespace: hapi-operator-sample
  labels:
    "configZone": "hapi-operator-sample"
    "packageId": "c82396e5fc13ef7bbf6bc078502a21e4"
spec:
  hosts:
    - hapi-sample.mse-daily.terminus.io
  path: /s
  backend:
    redirectBy: url
    serviceName: go-httpbin
    servicePort: 80
    upstreamHost: baidu.com
    rewriteTarget: /s
  policy:
    auth:
      authType: sign-auth
      switch: true
      global: false
    safetyIP:
      blackListSourceRange: ""
      domainBlackListSourceRange: ""
      domainWhiteListSourceRange: ""
      ipType: x-peer-ip
      keyRateLimitingValue: 12 query_per_second
      global: true
      switch: false
      whiteListSourceRange: 123.45.67.1/18
